# Generated by Django 5.2.7 on 2025-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_user_type_patientreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc'), (3, 'pat')], default=1, max_length=50),
        ),
    ]
